### ISSUE TITLE
`NewCluster` has `node_type_id` as mandatory

### ISSUE THREAD

**Issue by avishniakov** [PrefectHQ/prefect-databricks#26]
Hi,

in current implementation of `NewCluster` it is not possible to pass in only `instance_pool_id`, because `node_type_id` is mandatory field. Obviously, if we pass both it will fail on cluster creation on Databricks side, since `instance_pool_id` and `node_type_id` are self-excluding settings for a cluster.

I can contribute to the package myself, if I'm assigned with necessary permissions (just not sure how contributing works for `prefect-databricks` and if it is allowed by maintainers).

## Errors
```
>>> NewCluster(instance_pool_id="ABC", spark_version="10.4.x-scala2.12")
---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
Cell In [37], line 1
----> 1 NewCluster(instance_pool_id="ABC", spark_version="10.4.x-scala2.12")

File ~/Projects/GitHub/Libs/mls-mlops/.venv/lib/python3.8/site-packages/pydantic/main.py:342, in pydantic.main.BaseModel.__init__()

ValidationError: 1 validation error for NewCluster
node_type_id
  field required (type=value_error.missing)
```

```
>>> NewCluster(node_type_id="m5d.xlarge", instance_pool_id="ABC", spark_version="10.4.x-scala2.12")
Malformed Request from Databricks
```

**Comment by ahuang11** [comment]
Hi thanks for reporting this!

https://github.com/PrefectHQ/prefect-databricks/pull/25 should fix this.
